name: Periodic checks

on:
  #push:
  #  branches:
  #    - master
  schedule:
    - cron: '15 5 * * 1,3,5'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://damp-brook-37876.herokuapp.com/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s